FROM golang:1.25-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /bin/amlak-media-optimizer ./cmd/media-optimizer

FROM alpine:3.22
RUN apk add --no-cache ffmpeg
WORKDIR /app
COPY --from=build /bin/amlak-media-optimizer /usr/local/bin/amlak-media-optimizer
EXPOSE 8094
CMD ["amlak-media-optimizer"]
