FROM golang:1.25-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /bin/amlak-search ./cmd/search

FROM alpine:3.22
WORKDIR /app
COPY --from=build /bin/amlak-search /usr/local/bin/amlak-search
EXPOSE 8091
CMD ["amlak-search"]
