FROM golang:1.25-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /bin/amlak-realtime ./cmd/realtime

FROM alpine:3.22
WORKDIR /app
COPY --from=build /bin/amlak-realtime /usr/local/bin/amlak-realtime
EXPOSE 8090
CMD ["amlak-realtime"]
