FROM golang:1.23-bookworm AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /bin/amlak-file-service ./cmd/file-service

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends ffmpeg ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=build /bin/amlak-file-service /usr/local/bin/amlak-file-service
EXPOSE 8095
CMD ["amlak-file-service"]
